import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
st.set_page_config(page_title="Airbnb Dashboard", layout="wide")
sns.set(style="whitegrid")
df = pd.read_csv("cleaned_airbnb_data.csv")
st.sidebar.header("Filters")
locations = st.sidebar.multiselect("Select Location(s)", options=df['Location'].unique(), default=df['Location'].unique())
beds = st.sidebar.slider("Number of Beds", int(df['Beds'].min()), int(df['Beds'].max()), (1, 5))
filtered_df = df[(df['Location'].isin(locations)) & (df['Beds'].between(*beds))]
st.title("📊 Airbnb Price Analytics Dashboard")
col1, col2, col3 = st.columns(3)
col1.metric("Average Price (USD)", f"${filtered_df['Price (USD)'].mean():.2f}")
col2.metric("Average Rating", f"{filtered_df['Rating'].mean():.2f}")
col3.metric("Total Listings", f"{len(filtered_df)}")
st.subheader("💰 Price Distribution")
fig1, ax1 = plt.subplots()
sns.histplot(filtered_df['Price (USD)'], bins=30, kde=True, ax=ax1)
st.pyplot(fig1)
st.subheader("📍 Average Price by Location")
fig2, ax2 = plt.subplots()
avg_price = filtered_df.groupby("Location")["Price (USD)"].mean().sort_values()
avg_price.plot(kind="barh", ax=ax2, color="teal")
st.pyplot(fig2)
st.subheader("⭐ Price vs. Rating")
fig3, ax3 = plt.subplots()
sns.scatterplot(data=filtered_df, x="Rating", y="Price (USD)", hue="Location", ax=ax3)
st.pyplot(fig3)
st.subheader("🛏 Beds vs. Price")
fig4, ax4 = plt.subplots()
sns.boxplot(x='Beds', y='Price (USD)', data=filtered_df, palette="Set3", ax=ax4)
st.pyplot(fig4)
st.subheader("🏠 Listings by Location")
fig5, ax5 = plt.subplots()
sns.countplot(y='Location', data=filtered_df, order=filtered_df['Location'].value_counts().index, ax=ax5)
st.pyplot(fig5)
